_core:
  default_config_hash: RePADAH4yHzDAKh-gEsDxPFK9hQe32l4p4t8Cqryww8
langcode: en
uuid: 2d177665-41c3-44d0-9617-fdc03a5b593f
name: 'Marco Gandi'
mail: gandi.marco@gmail.com
slogan: 'A blogging profile for Tome users'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
